version: 3.8
services:
  vuehr:
    image: node:14.14-alpine
    command: sh -c "npm install && npm run serve"
    port: 8080:8080
    working_dir: /vuehr
    volumes:
      - ./:/vuehr
  backend:
    image: openjdk:8-jdk-alpine
    
    
  
